// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuHkIHANcZYneX7eGXFWUm3oOgiSndcME',
    appId: '1:721500559508:android:7d96ff80556e0e4dcabc81',
    messagingSenderId: '721500559508',
    projectId: 'geotemp-a2491',
    databaseURL: 'https://geotemp-a2491-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'geotemp-a2491.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcbYzaPb4Vm28p7lnUMBl--Rtsm_vxkVE',
    appId: '1:721500559508:ios:6c9cd737aa09f547cabc81',
    messagingSenderId: '721500559508',
    projectId: 'geotemp-a2491',
    databaseURL: 'https://geotemp-a2491-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'geotemp-a2491.appspot.com',
    androidClientId: '721500559508-0f4k5t4m0frq8e5rdlppobmiisutbkd9.apps.googleusercontent.com',
    iosBundleId: 'com.uietconnectue203093.uietconnect',
  );
}
