class clubdecription {
  String mitra1 =
      "MITRA TOUCHING LIVES is an N.G.O of University Institute of Engineering and Technology(UIET) of Panjab University,Chandigarh.As the name suggests ‘MITRA’ our N.G.O helps people as Friends. It indicates connectivity of our N.G.O with environment, social well being and society at large.\n\nIt was initiated in 2004 by Gurveen Bhatia, former student of UIET and now the presidentof Mitra is Mr Kamal Goudha and Ms Ayushi Garg. \n\nMitra Touching Lives is  self fund raiser and working for a good cause. We organize many fun events at different platforms and fund which is collected through these events is used for humanity and social services.It is really a good platform for new start-ups and Business firms to publicize their firms and start-ups among Chandigarh city and university students.";
  String mitralink =
      "https://mitratouchinglives.wordpress.com/author/mitratouchinglives/";
  String pclub =
      "P Club UIET is the Programming Club at University Institute of Engineering and Technology (UIET), Panjab University1. It is a student-run club that aims to promote and foster a culture of programming and problem-solving among the students of UIET2. \n\nThe club organizes various events and activities such as workshops, hackathons, coding competitions, and guest lectures to help students learn new skills and technologies3. The club also has a website2 and a Facebook page3 where they share their updates and achievements. \n\nP Club UIET is a platform for students who are passionate about coding and want to collaborate with other like-minded peers.";
  String pClublink = "https://www.facebook.com/pclubuiet/";
  String magboard =
      "The official college magazine QUIET which has been a huge success over the past few years, the MAGBOARD of UIET has played a vital role in compiling the year round activities and data, including the info about the previous and current semester happenings in a very originative format. \n\nNot only the college magazine, the MAGBOARD also has successfully published VINE, the farewell magazine to passing out 4th years batch by compiling a book full of memories for every students, so that one takes with him a part of their wonderful 4 years to relive all the moments. \n\nApart from publishing magazines, the MAGBOARD has actively organized literary events including debates and quiz during college fest GOONJ, and has successfully accomplished to create an important image for themselves. For all those good at art, quizzing, public speaking, debating and discussions, Magboard has a lot in store for you.";
  String magboardlink = "https://uietadmissions.wordpress.com/magboard/";
  String star =
      "The STAR team was set up for managing the Alumni Affairs Office at UIET Chandigarh. It comprises of 13 students from all batches. \n\nThe STAR team has organized quite a few alumni events in the campus including an Alumni Reunion which was a huge success. Working in an office, the students learn about managing affairs and settling disputes. \n\nSome of the members are working on a goal to complete the database of all graduates of UIET. Other members work on publications, content and engagement.";
  String starlink = "https://uietadmissions.wordpress.com/star/";
}
